name: s5p-wrfchem
channels:
  - conda-forge
dependencies:
  - python>=3.8
  # base
  - numpy
  - matplotlib=3.3.4
  - pandas
  - scipy
  - configparser
  # scientific data
  - netcdf4
  - xarray
  - h5py
  - dask
  # map and plot
  - cartopy
  - pyproj
  - proplot
  - xesmf
  - xgcm
  # others
  - satpy>=0.27.0
  - wrf-python
