name: s5p-wrfchem
channels:
  - conda-forge
dependencies:
  - python>=3.7
  # base
  - numpy
  - matplotlib
  - pandas
  - scipy
  - configparser
  # scientific data
  - netcdf4
  - xarray
  - h5py
  - dask
  # map and plot
  - cartopy
  - pyproj
  - proplot
  - xesmf
  - xgcm
  # others
  - satpy
  - wrf-python
